project:
  type: website
  preview:
    port: 4200
  resources:
    - "*.png"
    - "*.mp4"

website:
  open-graph: true
  twitter-card:
    creator: "@wasimlorgat"
    site: "@wasimlorgat"
  title: "Wasim Lorgat"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - text: Posts
        file: index.qmd
      - projects.qmd
      - tils/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/wasimlorgat
      - icon: github
        href: https://github.com/seem
      - icon: linkedin
        href: https://linkedin.com/in/wasim-lorgat
      - icon: rss
        text: Posts
        href: index.xml
      - icon: rss
        text: TILs
        href: tils/index.xml

  site-url: https://wasimlorgat.com

format:
  html:
    theme: seem.scss
    include-in-header: [analytics-head.html]
    include-after-body: [analytics-body.html]

comments:
  giscus: 
    repo: seem/blog
    repo-id: R_kgDOIBWk3A
    category: Announcements
    category-id: DIC_kwDOIBWk3M4CSSa6
    mapping: pathname
    loading: lazy
    input-position: top
