project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  open-graph: true
  twitter-card:
    creator: "@wasimlorgat"
    site: "@wasimlorgat"
  title: "Wasim Lorgat"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - text: Posts
        file: index.qmd
      - tils/index.qmd
      - projects.qmd
    right:
      - icon: twitter
        href: https://twitter.com/wasimlorgat
      - icon: github
        href: https://github.com/seem
      - icon: linkedin
        href: https://linkedin.com/in/wasim-lorgat
  site-url: https://wasimlorgat.com
format:
  html:
    theme: seem.scss
