project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  open-graph: true
  twitter-card:
    creator: "@wasimlorgat"
    site: "@wasimlorgat"
  title: "Wasim Lorgat"
  favicon: favicon.ico
  navbar:
    background: dark
    left:
      - posts/index.qmd
      - tils/index.qmd
      - projects.qmd
    right:
      - icon: twitter
        href: https://twitter.com/wasimlorgat
      - icon: github
        href: https://github.com/seem
  site-url: https://wasimlorgat.com
format:
  html:
    theme: journal
    css: styles.css
