project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "Wasim Lorgat"
  navbar:
    background: dark
    left:
      - posts/index.qmd
      - tils/index.qmd
      - projects.qmd
    right:
      - icon: twitter
        href: https://twitter.com/wasimlorgat
      - icon: github
        href: https://github.com/seem
format:
  html:
    theme: journal
    css: styles.css
